services:

  solana-event-listener:
#    build:
#      dockerfile: ./Dockerfile
    image: registry.tradefiapp.com:5443/solana-event-listener:v1
    container_name: solana-event-listener
    hostname: solana-event-listener
    #    ports:
    #      - "5000:5000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka0:19092
      - MYSQL_HOST=mysql8
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=solana_db
      - MYSQL_USER=solana_user
      - MYSQL_PASSWORD=password
      - SOLANA_RPC=https://api.devnet.solana.com
      - SOLANA_WEBSOCKET=wss://api.devnet.solana.com
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - marketbroker_net
    profiles: [prop-trade-bundle]
    depends_on:
      kafka0:
        condition: service_healthy
      mysql8:
        condition: service_healthy

  # tradefi-app:
  #   container_name: tradefi-app
  #   hostname: tradefi-app
  #   image: registry.tradefiapp.com:5443/tradefi-app:1.0.0
  #   ports:
  #     - "127.0.0.1:3001:3000"
  #   networks:
  #     - marketbroker_net
  #   profiles: [prop-trade-bundle]
  #   depends_on:
  #     mongodb:
  #       condition: service_healthy
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 256M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 128M
  #   restart: always

  # mongodb:
  #   image: mongo:8.0.16-noble
  #   container_name: mongodb
  #   hostname: mongodb
  #   restart: always
  #   ports:
  #     - "127.0.0.1:27017:27017" # Expose MongoDB on the default port
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root # Set the admin username
  #     MONGO_INITDB_ROOT_PASSWORD: password # Set the admin password
  #   volumes:
  #     - mongo-data:/data/db # Persist MongoDB data
  #     - mongo-config:/data/configdb # Persist MongoDB configuration
  #   networks:
  #     - marketbroker_net
  #   profiles: [prop-trade-bundle]
  #   healthcheck:
  #     test: ["CMD", "mongosh", "--eval", 'db.runCommand("ping").ok']
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3

  # mongo-express:
  #   container_name: mongo-express
  #   hostname: mongo-express
  #   image: mongo-express:1.0-20-alpine3.19
  #   restart: always
  #   ports:
  #     - "127.0.0.1:8084:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/
  #   networks:
  #     - marketbroker_net
  #   profiles: [prop-trade-bundle]
  #   depends_on:
  #     - mongodb


  nginx-tradefi:
    container_name: nginx-tradefi
    image: "nginx:1.28.1-alpine3.23"
    ports:
      - "443:443"
      - "80:80"
      - "8000-8009:8000-8009"
    volumes:
      - ./docker/nginx:/etc/nginx
      - ./docker/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available/
#      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - marketbroker_net
    profiles: [prop-trade-bundle]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    restart: always


# volumes:
  # mongo-data:
  # mongo-config:

networks:
  marketbroker_net:
    name: marketbroker_net-network
    external: true
