kapt.use.worker.api=true

nexusDomain=nexus.tools.v2.symmetrical.ai
nexusUser=
nexusPassword=
artifactVersion=
appVersion=

# this is required for SonarQube scans to work
org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=512m


# org.gradle.java.home=/Users/tzieleniewski/.sdkman/candidates/java/17.0.4.1-tem
org.gradle.java.home=/Users/tzieleniewski/.sdkman/candidates/java/current