management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health,info,prometheus,beans,configprops,loggers,env
  server:
    port: 8090
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3

  zipkin:
    tracing:
      endpoint: http://tempo:9411

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true # (1)

  observations:
    key-values:
      application: marketbroker


server:
  http2.enabled: true

spring:
  application:
    name: marketbroker
  profiles:
    active: request-response-logging
  jackson:
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: marketbroker
      max-poll-records: 1
    listener:
      ack-mode: record
      concurrency: 1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://sso.keycloak-01.dev.v2.symmetrical.ai/auth/realms/mobile"
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: marketbroker
            client-secret: ${AI_SYMMETRICAL_KEYCLOAK_CLIENT_SECRET}
        provider:
          keycloak:
            token-uri: "https://sso.keycloak-01.dev.v2.symmetrical.ai/auth/realms/mobile/protocol/openid-connect/token"

  datasource:
    url: jdbc:h2:mem:testdb           #jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true


#spring.datasource.url=jdbc:h2:file:/data/demo


#  main:
#    banner-mode: off
#      location: classpath:/banner.txt

logging:
  level:
    ROOT: INFO
    com.piotr.marketbroker: DEBUG
    org.springframework.security: INFO
    ai.symmetrical.kafka.common.logging: DEBUG
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

com.piotr.marketbroker:
  security:
    openid-connect-configuration-url: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/.well-known/openid-configuration
    enabled: false
    ignored-urls: [ /openapi.yaml,
                    /health/**, /info/**, /prometheus/**,
                    /v3/**,
                    /v3/api-docs,
                    /configuration/ui, /configuration/security,
                    /swagger-resources/**, /swagger-ui/**,
                    /webjars/**,
                    /favicon.ico,
                    /*/*.png, /*/*.gif, /*/*.svg, /*/*.jpg, /*/*.css, /*/*.js ]

com.piotr:
  cors:
    enabled: false
    headers: "*"
    domain: "*"
    exposed-headers: ""
  testcontainers:
    kafka:
      enabled: false


ai.symmetrical:
  kafka:
    env: local
    default-partitions-number: 1
    default-replicas-number: 1
    default-dlt-replicas-number: 1
    consumer:
      enabled: false
      listener:
        concurrency: 1
      scan-package: com.piotr.marketbroker.application.event
      backoff:
        interval: 1000
        max-attempts: 1
    producer:
      enabled: true
      scan-package: com.piotr.marketbroker.application.event


websocket:
  server: "wss://demo-api.finsa.com.au/"

