spring:
  kafka:
    bootstrap-servers: kafka0:19092
  datasource:
    url: jdbc:mysql://mysql8:3306/marketbroker
com.piotr:
  kafkaconnect:
    url: http://kafka-connect:8083
  questdb:
    url: http://questdb:9000
  loki:
    host: loki:3100
management:
  zipkin:
    tracing:
      endpoint: http://tempo:9411
