management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      base-path: /
      exposure:
        include: health,info,prometheus,startup
  server:
    port: 8090
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411


  observations:
    key-values:
      application: marketbroker


server:
  http2.enabled: true

spring:
  application:
    name: marketbroker
  profiles:
    active: default
#    active: request-response-logging
  jackson:
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: marketbroker
      max-poll-records: 1
    listener:
      ack-mode: record
      concurrency: 1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth-server:9000"
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: marketbroker
            client-secret: marketbroker
        provider:
          keycloak:
            token-uri: "https://auth-server/auth/realms/mobile/protocol/openid-connect/token"

  datasource:
#    url: jdbc:h2:mem:testdb           #jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=false;


  jpa:
    generate-ddl: true
    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

#  main:
#    banner-mode: off
#      location: classpath:/banner.txt

logging:
  level:
    ROOT: INFO
    com.piotr.marketbroker: DEBUG
    ai.symmetrical.kafka.common.logging: INFO
    org.apache.http: DEBUG
    org.springframework:
      web: DEBUG
      security: INFO
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"



com.piotr.marketbroker:
  security:
    openid-connect-configuration-url: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/.well-known/openid-configuration
    enabled: false
    ignored-urls: [ /openapi.yaml,
                    /health/**, /info/**, /prometheus/**,
                    /v3/**,
                    /v3/api-docs/**,
                    /configuration/ui, /configuration/security,
                    /swagger-resources/**, /swagger-ui/**,
                    /webjars/**,
                    /favicon.ico,
                    /h2-console/**,
                    /*/*.png, /*/*.gif, /*/*.svg, /*/*.jpg, /*/*.css, /*/*.js ]
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080
com.piotr:
#  cors:
#    enabled: false
#    headers: "*"
#    domain: "*"
#    exposed-headers: ""
  testcontainers:
    kafka:
      enabled: false
  kafka-connect:
    url: http://localhost:8083
    questdb-host: questdb:9000
  questdb:
    url: http://localhost:9000
  loki:
    host: localhost:3100

ai.symmetrical:
  kafka:
    env: local
    default-partitions-number: 1
    default-replicas-number: 1
    default-dlt-replicas-number: 1
    consumer:
      enabled: false
      listener:
        concurrency: 1
      scan-package: com.piotr.marketbroker.application.event
      backoff:
        interval: 1000
        max-attempts: 1
    producer:
      enabled: true
      scan-package: com.piotr.marketbroker.application.event


java:
  util:
    logging:
      ConsoleHandler:
        formatter: java.util.logging.SimpleFormatter
        level: ALL
org:
  apache:
    http:
      impl:
        conn:
          level: FINEST
    commons:
      logging:
        Log: org.apache.commons.logging.impl.SimpleLog
        simplelog:
          showdatetime: true
          log:
            httpclient:
              wire:
                header: debug
            org:
              apache:
                commons:
                  httpclient: debug

springdoc:
#  packages-to-scan: com.piotr.marketbroker.application.controller
#  show-actuator: true
  api-docs:
#    path: /api-docs
    enabled: true
#  paths-to-match: /**
swagger-ui:
  tryItOutEnabled: true
