spring:
  kafka:
    bootstrap-servers: kafka0:29092
com.piotr:
  kafka-connect:
    url: http://kafka-connect:8083
  questdb:
    url: http://questdb:9000
  loki:
    host: loki:3100
management:
  zipkin:
    tracing:
      endpoint: http://tempo:9411
