openapi: 3.0.1
info:
  title: marketbrokers API
  version: v1
  description: marketbrokers API
  contact:
    name: dev@symmetrical.ai
servers:
  - url: 'http://localhost:8080'
    description: Server url
paths:
  '/messages/{id}':
    put:
      operationId: updateMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: employerId
          in: header
          description: Used by clients (services) to set employer context. Ignored for public APIs (end-users/bff) - EmployerId is fetched from JWT token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMessageRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UpdateMessageResponse'
      summary: Update message
      description: Update message
      tags:
        - CreateMessage
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Message Id
    patch:
      summary: Set message status
      operationId: setMessageStatus
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      description: Set message status
      parameters:
        - schema:
            type: string
          in: header
          name: employerId
          description: Used by clients (services) to set employer context. Ignored for public APIs (end-users/bff) - EmployerId is fetched from JWT token
      tags:
        - ReadMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetMessageStatusRequest'
  /messages:
    post:
      operationId: createMessage
      parameters:
        - name: employerId
          in: header
          description: Used by clients (services) to indicate employer context. Ignored for public APIs (end-users/bff)
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMessageRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateMessageResponse'
      summary: Create message
      description: Create message
      tags:
        - CreateMessage
    parameters: []
    get:
      summary: Fetch messages
      operationId: getMessages
      responses:
        '200':
          description: OK
      tags:
        - ReadMessage
      description: Fetch messages using filters
      parameters:
        - schema:
            type: string
          in: header
          name: employerId
          description: Used by clients (services) to indicate employer context. Ignored for public APIs (end-users/bff)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMessageCriteria'
  /marketbroker/test:
    get:
      tags:
        - Test
      operationId: test
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
      summary: Api test
      description: Api test
  /messages/revoke:
    post:
      summary: Revoke messages
      operationId: revokeMessage
      responses:
        '200':
          description: OK
      description: Revoke messages using filters
      tags:
        - CreateMessage
      parameters:
        - schema:
            type: string
          in: header
          name: employerId
          description: Used by clients (services) to indicate employer context. Ignored for public APIs (end-users/bff)
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RevokeMessageCriteria'
        description: Revoke message filter
components:
  schemas:
    Content:
      type: object
      properties:
        title:
          type: string
        subTitle:
          type: string
        body:
          type: string
        actionUri:
          type: string
          x-stoplight:
            id: 10q5ljqsqsplz
      required:
        - title
        - body
    CreateMessageRequest:
      type: object
      x-stoplight:
        id: 04fff2ac08b57
      properties:
        recipientType:
          $ref: '#/components/schemas/UserType'
        recipients:
          type: array
          minItems: 1
          items:
            type: string
            minLength: 1
        objectClass:
          type: string
        objectReference:
          type: string
          format: uuid
        content:
          $ref: '#/components/schemas/Content'
        state:
          $ref: '#/components/schemas/State'
        validity:
          type: string
          format: date-time
        actionable:
          type: boolean
        replicate:
          type: boolean
          x-stoplight:
            id: wni0ypz2qn8yl
      required:
        - recipientType
        - recipients
        - objectClass
        - objectReference
        - content
        - state
        - validity
        - actionable
        - replicate
    UpdateMessageRequest:
      type: object
      x-stoplight:
        id: gvfqwurxf2z6t
      properties:
        content:
          $ref: '#/components/schemas/Content'
        state:
          $ref: '#/components/schemas/State'
        validity:
          type: string
          format: date-time
        actionable:
          type: boolean
        recipientType:
          $ref: '#/components/schemas/UserType'
        recipients:
          type: array
          x-stoplight:
            id: teixzvtgx7a9t
          items:
            x-stoplight:
              id: l4prfrvk5t29n
            type: string
    FieldErrorResponse:
      required:
        - error
        - field
      type: object
      properties:
        field:
          type: string
        error:
          type: string
    UpdateMessageResponse:
      required:
        - errors
        - id
        - isCorrect
      type: object
      properties:
        id:
          type: string
          format: uuid
        isCorrect:
          type: boolean
        errors:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/FieldErrorResponse'
    CreateMessageResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        isCorrect:
          type: boolean
        errors:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/FieldErrorResponse'
      required:
        - id
        - isCorrect
        - errors
    SetMessageStatusRequest:
      title: SetMessageStatusRequest
      x-stoplight:
        id: vqb9o7xq52kal
      type: object
      properties:
        read:
          type: boolean
          x-stoplight:
            id: vnu1sbr0886qk
        handled:
          type: boolean
          x-stoplight:
            id: st6134x069mtg
    State:
      title: State
      x-stoplight:
        id: db2qf71evhkfo
      type: string
      enum:
        - ALERT
        - INFO
        - SUCCESS
        - ERROR
    UserType:
      title: UserType
      x-stoplight:
        id: ystl0tqv10m6k
      type: string
      enum:
        - USER
        - SYSTEM
    OriginatorType:
      title: OriginatorType
      x-stoplight:
        id: ht67q49qigzpd
      type: string
      enum:
        - SYSTEM
        - USER
    RevokeMessageCriteria:
      title: RevokeMessageCriteria
      x-stoplight:
        id: b69n2vbel9c6s
      type: object
      properties:
        messageId:
          type: string
          format: uuid
          description: Message Id
        objectReference:
          type: string
          format: uuid
          description: Object reference
        objectClass:
          type: string
          description: Object class
        state:
          type: array
          description: State
          items:
            $ref: '#/components/schemas/State'
        originatorType:
          $ref: '#/components/schemas/OriginatorType'
        originator:
          type: string
          description: Originator Id
        recipientType:
          $ref: '#/components/schemas/UserType'
        recipient:
          type: string
          description: Recipient id
        createdFrom:
          type: string
          description: Earliest creation datetime
          format: date-time
    GetMessageCriteria:
      title: GetMessageCriteria
      x-stoplight:
        id: 3vk6l4nr7y2wk
      type: object
      properties:
        objectClass:
          type: string
          description: Object class
        objectReference:
          type: string
          format: uuid
          description: Object reference
        recipientType:
          $ref: '#/components/schemas/UserType'
        recipientId:
          type: string
          description: Recipient Id
        readStatus:
          type: string
          description: Read flag
        state:
          type: array
          description: State
          items:
            $ref: '#/components/schemas/State'
        createdFrom:
          type: string
          description: Earliest creation datetime
tags:
  - name: CreateMessage
  - name: ReadMessage
  - name: Test
