name=questdb-sink
topics=TICKSTREAM_TOPIC
table=tick_table
client.conf.string=http::addr=questdb:9009;

connector.class=io.questdb.kafka.QuestDBSinkConnector

# message format configuration
value.converter=org.apache.kafka.connect.json.JsonConverter
include.key=false
key.converter=org.apache.kafka.connect.storage.StringConverter
#key.converter.schemas.enable=false
value.converter.schemas.enable=false
#timestamp.field.name=t
#timestamp.units=seconds
timestamp.kafka.native=true
#symbols=