{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.symmetrical",
    "module": "sym-kafka",
    "version": "7.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.springframework.kafka",
          "module": "spring-kafka"
        }
      ],
      "files": [
        {
          "name": "sym-kafka-7.4.1.jar",
          "url": "sym-kafka-7.4.1.jar",
          "size": 43774,
          "sha512": "4273a9b51f89caf2806515a95b6170515935e99036a2e0535a6c24b183ebbbb792d8a664208b143528cc60fd78a66970ed772a84f7efe47321b629f9fc6086c7",
          "sha256": "6c3bce90877a54f35f28d5b7f8f84c0ccffcd77a163a1262519e54186bed7740",
          "sha1": "42e247d924f0c100d742775ef5a0f69df6dece0a",
          "md5": "9fff022f79b117a739a5ef7267d5ba73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "ai.symmetrical",
          "module": "sym-kafka-annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.springframework.kafka",
          "module": "spring-kafka"
        }
      ],
      "files": [
        {
          "name": "sym-kafka-7.4.1.jar",
          "url": "sym-kafka-7.4.1.jar",
          "size": 43774,
          "sha512": "4273a9b51f89caf2806515a95b6170515935e99036a2e0535a6c24b183ebbbb792d8a664208b143528cc60fd78a66970ed772a84f7efe47321b629f9fc6086c7",
          "sha256": "6c3bce90877a54f35f28d5b7f8f84c0ccffcd77a163a1262519e54186bed7740",
          "sha1": "42e247d924f0c100d742775ef5a0f69df6dece0a",
          "md5": "9fff022f79b117a739a5ef7267d5ba73"
        }
      ]
    }
  ]
}
