version = 5.2.2
archive_dir = /etc/letsencrypt/archive/trade.tradefiapp.com
cert = /etc/letsencrypt/live/trade.tradefiapp.com/cert.pem
privkey = /etc/letsencrypt/live/trade.tradefiapp.com/privkey.pem
chain = /etc/letsencrypt/live/trade.tradefiapp.com/chain.pem
fullchain = /etc/letsencrypt/live/trade.tradefiapp.com/fullchain.pem
[renewalparams]
account = 2b3891a41e56685cb03c58c3e71f3b5d
pref_challs = dns-01,
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
